spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/ema?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
